// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type TestApiReq struct {
	InputParams string `json:"input_params,optional"`
}

type TestApiRsp struct {
	OutputParams string `json:"output_params"`
}
