// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc1.proto

package server

import (
	"context"

	"demo2/app/rpc1/internal/logic"
	"demo2/app/rpc1/internal/svc"
	"demo2/app/rpc1/rpc1_pb"
)

type Rpc1Server struct {
	svcCtx *svc.ServiceContext
	rpc1_pb.UnimplementedRpc1Server
}

func NewRpc1Server(svcCtx *svc.ServiceContext) *Rpc1Server {
	return &Rpc1Server{
		svcCtx: svcCtx,
	}
}

func (s *Rpc1Server) TestC(ctx context.Context, in *rpc1_pb.TestCReq) (*rpc1_pb.TestCRsp, error) {
	l := logic.NewTestCLogic(ctx, s.svcCtx)
	return l.TestC(in)
}
