// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tAccountFlowFieldNames          = builder.RawFieldNames(&TAccountFlow{})
	tAccountFlowRows                = strings.Join(tAccountFlowFieldNames, ",")
	tAccountFlowRowsExpectAutoSet   = strings.Join(stringx.Remove(tAccountFlowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tAccountFlowRowsWithPlaceHolder = strings.Join(stringx.Remove(tAccountFlowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tAccountFlowModel interface {
		Insert(ctx context.Context, data *TAccountFlow) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TAccountFlow, error)
		FindOneByUidFlowTypeFlowId(ctx context.Context, uid int64, flowType int64, flowId string) (*TAccountFlow, error)
		Update(ctx context.Context, data *TAccountFlow) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTAccountFlowModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TAccountFlow struct {
		Id         int64     `db:"id"`        // 主键
		Uid        int64     `db:"uid"`       // 用户UID
		UserId     string    `db:"user_id"`   // 用户ID
		FlowId     string    `db:"flow_id"`   // 流水ID
		FlowType   int64     `db:"flow_type"` // 流水类型
		BizType    int64     `db:"biz_type"`  // 业务类型
		Amount     int64     `db:"amount"`    // 金额
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTAccountFlowModel(conn sqlx.SqlConn) *defaultTAccountFlowModel {
	return &defaultTAccountFlowModel{
		conn:  conn,
		table: "`t_account_flow`",
	}
}

func (m *defaultTAccountFlowModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTAccountFlowModel) FindOne(ctx context.Context, id int64) (*TAccountFlow, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tAccountFlowRows, m.table)
	var resp TAccountFlow
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAccountFlowModel) FindOneByUidFlowTypeFlowId(ctx context.Context, uid int64, flowType int64, flowId string) (*TAccountFlow, error) {
	var resp TAccountFlow
	query := fmt.Sprintf("select %s from %s where `uid` = ? and `flow_type` = ? and `flow_id` = ? limit 1", tAccountFlowRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid, flowType, flowId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAccountFlowModel) Insert(ctx context.Context, data *TAccountFlow) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tAccountFlowRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.FlowId, data.FlowType, data.BizType, data.Amount)
	return ret, err
}

func (m *defaultTAccountFlowModel) Update(ctx context.Context, newData *TAccountFlow) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tAccountFlowRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Uid, newData.UserId, newData.FlowId, newData.FlowType, newData.BizType, newData.Amount, newData.Id)
	return err
}

func (m *defaultTAccountFlowModel) tableName() string {
	return m.table
}
