// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tAccountFieldNames          = builder.RawFieldNames(&TAccount{})
	tAccountRows                = strings.Join(tAccountFieldNames, ",")
	tAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(tAccountFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(tAccountFieldNames, "`uid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tAccountModel interface {
		Insert(ctx context.Context, data *TAccount) (sql.Result, error)
		FindOne(ctx context.Context, uid int64) (*TAccount, error)
		Update(ctx context.Context, data *TAccount) error
		Delete(ctx context.Context, uid int64) error
	}

	defaultTAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TAccount struct {
		Uid        int64     `db:"uid"`     // 主键
		UserId     string    `db:"user_id"` // 用户ID
		Balance    int64     `db:"balance"` // 余额
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTAccountModel(conn sqlx.SqlConn) *defaultTAccountModel {
	return &defaultTAccountModel{
		conn:  conn,
		table: "`t_account`",
	}
}

func (m *defaultTAccountModel) Delete(ctx context.Context, uid int64) error {
	query := fmt.Sprintf("delete from %s where `uid` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, uid)
	return err
}

func (m *defaultTAccountModel) FindOne(ctx context.Context, uid int64) (*TAccount, error) {
	query := fmt.Sprintf("select %s from %s where `uid` = ? limit 1", tAccountRows, m.table)
	var resp TAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTAccountModel) Insert(ctx context.Context, data *TAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.Balance)
	return ret, err
}

func (m *defaultTAccountModel) Update(ctx context.Context, data *TAccount) error {
	query := fmt.Sprintf("update %s set %s where `uid` = ?", m.table, tAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Balance, data.Uid)
	return err
}

func (m *defaultTAccountModel) tableName() string {
	return m.table
}
