// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUserInfoFieldNames          = builder.RawFieldNames(&TUserInfo{})
	tUserInfoRows                = strings.Join(tUserInfoFieldNames, ",")
	tUserInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(tUserInfoFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tUserInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(tUserInfoFieldNames, "`uid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tUserInfoModel interface {
		Insert(ctx context.Context, data *TUserInfo) (sql.Result, error)
		FindOne(ctx context.Context, uid int64) (*TUserInfo, error)
		Update(ctx context.Context, data *TUserInfo) error
		Delete(ctx context.Context, uid int64) error
	}

	defaultTUserInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TUserInfo struct {
		Uid        int64     `db:"uid"`     // 主键
		UserId     string    `db:"user_id"` // 用户ID
		Name       string    `db:"name"`    // 用户名
		Age        int64     `db:"age"`     // 年龄
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTUserInfoModel(conn sqlx.SqlConn) *defaultTUserInfoModel {
	return &defaultTUserInfoModel{
		conn:  conn,
		table: "`t_user_info`",
	}
}

func (m *defaultTUserInfoModel) Delete(ctx context.Context, uid int64) error {
	query := fmt.Sprintf("delete from %s where `uid` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, uid)
	return err
}

func (m *defaultTUserInfoModel) FindOne(ctx context.Context, uid int64) (*TUserInfo, error) {
	query := fmt.Sprintf("select %s from %s where `uid` = ? limit 1", tUserInfoRows, m.table)
	var resp TUserInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserInfoModel) Insert(ctx context.Context, data *TUserInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tUserInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.UserId, data.Name, data.Age)
	return ret, err
}

func (m *defaultTUserInfoModel) Update(ctx context.Context, data *TUserInfo) error {
	query := fmt.Sprintf("update %s set %s where `uid` = ?", m.table, tUserInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Age, data.Uid)
	return err
}

func (m *defaultTUserInfoModel) tableName() string {
	return m.table
}
