// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUserFieldNames          = builder.RawFieldNames(&TUser{})
	tUserRows                = strings.Join(tUserFieldNames, ",")
	tUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tUserRowsWithPlaceHolder = strings.Join(stringx.Remove(tUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTUserIdPrefix = "cache:tUser:id:"
)

type (
	tUserModel interface {
		Insert(ctx context.Context, data *TUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUser, error)
		Update(ctx context.Context, data *TUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUserModel struct {
		sqlc.CachedConn
		table string
	}

	TUser struct {
		Id         int64     `db:"id"`   // 主键
		Name       string    `db:"name"` // 用户名
		Age        int64     `db:"age"`  // 年龄
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTUserModel {
	return &defaultTUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_user`",
	}
}

func (m *defaultTUserModel) Delete(ctx context.Context, id int64) error {
	tUserIdKey := fmt.Sprintf("%s%v", cacheTUserIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tUserIdKey)
	return err
}

func (m *defaultTUserModel) FindOne(ctx context.Context, id int64) (*TUser, error) {
	tUserIdKey := fmt.Sprintf("%s%v", cacheTUserIdPrefix, id)
	var resp TUser
	err := m.QueryRowCtx(ctx, &resp, tUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) Insert(ctx context.Context, data *TUser) (sql.Result, error) {
	tUserIdKey := fmt.Sprintf("%s%v", cacheTUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, tUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Age)
	}, tUserIdKey)
	return ret, err
}

func (m *defaultTUserModel) Update(ctx context.Context, data *TUser) error {
	tUserIdKey := fmt.Sprintf("%s%v", cacheTUserIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Age, data.Id)
	}, tUserIdKey)
	return err
}

func (m *defaultTUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTUserIdPrefix, primary)
}

func (m *defaultTUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTUserModel) tableName() string {
	return m.table
}
