// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: demo3.proto

package demo3

import (
	"context"

	"demo3redis/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetReq = types.GetReq
	GetRsp = types.GetRsp
	SetReq = types.SetReq
	SetRsp = types.SetRsp

	Demo3 interface {
		Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error)
		Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRsp, error)
	}

	defaultDemo3 struct {
		cli zrpc.Client
	}
)

func NewDemo3(cli zrpc.Client) Demo3 {
	return &defaultDemo3{
		cli: cli,
	}
}

func (m *defaultDemo3) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error) {
	client := types.NewDemo3Client(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

func (m *defaultDemo3) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRsp, error) {
	client := types.NewDemo3Client(m.cli.Conn())
	return client.Set(ctx, in, opts...)
}
