// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_mgr.proto

package server

import (
	"context"

	"demo5mysql/internal/logic"
	"demo5mysql/internal/svc"
	"demo5mysql/user_mgr_pb"
)

type UserMgrServer struct {
	svcCtx *svc.ServiceContext
	user_mgr_pb.UnimplementedUserMgrServer
}

func NewUserMgrServer(svcCtx *svc.ServiceContext) *UserMgrServer {
	return &UserMgrServer{
		svcCtx: svcCtx,
	}
}

// 用户相关
func (s *UserMgrServer) RegUser(ctx context.Context, in *user_mgr_pb.RegUserReq) (*user_mgr_pb.RegUserRsp, error) {
	l := logic.NewRegUserLogic(ctx, s.svcCtx)
	return l.RegUser(in)
}

func (s *UserMgrServer) GetUserInfo(ctx context.Context, in *user_mgr_pb.GetUserInfoReq) (*user_mgr_pb.GetUserInfoRsp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserMgrServer) UpdateUserInfo(ctx context.Context, in *user_mgr_pb.UpdateUserInfoReq) (*user_mgr_pb.UpdateUserInfoRsp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserMgrServer) GetUserFlow(ctx context.Context, in *user_mgr_pb.GetUserFlowReq) (*user_mgr_pb.GetUserFlowRsp, error) {
	l := logic.NewGetUserFlowLogic(ctx, s.svcCtx)
	return l.GetUserFlow(in)
}

func (s *UserMgrServer) GetUserBalance(ctx context.Context, in *user_mgr_pb.GetUserBalanceReq) (*user_mgr_pb.GetUserBalanceRsp, error) {
	l := logic.NewGetUserBalanceLogic(ctx, s.svcCtx)
	return l.GetUserBalance(in)
}

// 交易相关
func (s *UserMgrServer) Deposit(ctx context.Context, in *user_mgr_pb.DepositReq) (*user_mgr_pb.DepositRsp, error) {
	l := logic.NewDepositLogic(ctx, s.svcCtx)
	return l.Deposit(in)
}

func (s *UserMgrServer) Withdraw(ctx context.Context, in *user_mgr_pb.WithdrawReq) (*user_mgr_pb.WithdrawRsp, error) {
	l := logic.NewWithdrawLogic(ctx, s.svcCtx)
	return l.Withdraw(in)
}
