// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_mgr.proto

package usermgr

import (
	"context"

	"demo4mysql/user_mgr_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserReq  = user_mgr_pb.CreateUserReq
	CreateUserRsp  = user_mgr_pb.CreateUserRsp
	DeleteUserReq  = user_mgr_pb.DeleteUserReq
	DeleteUserRsp  = user_mgr_pb.DeleteUserRsp
	GetAllUsersReq = user_mgr_pb.GetAllUsersReq
	GetAllUsersRsp = user_mgr_pb.GetAllUsersRsp
	GetUserReq     = user_mgr_pb.GetUserReq
	GetUserRsp     = user_mgr_pb.GetUserRsp
	UpdateUserReq  = user_mgr_pb.UpdateUserReq
	UpdateUserRsp  = user_mgr_pb.UpdateUserRsp

	UserMgr interface {
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRsp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserRsp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRsp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRsp, error)
		GetAllUsers(ctx context.Context, in *GetAllUsersReq, opts ...grpc.CallOption) (*GetAllUsersRsp, error)
	}

	defaultUserMgr struct {
		cli zrpc.Client
	}
)

func NewUserMgr(cli zrpc.Client) UserMgr {
	return &defaultUserMgr{
		cli: cli,
	}
}

func (m *defaultUserMgr) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUserMgr) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserMgr) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserMgr) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUserMgr) GetAllUsers(ctx context.Context, in *GetAllUsersReq, opts ...grpc.CallOption) (*GetAllUsersRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.GetAllUsers(ctx, in, opts...)
}
