// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: demo3.proto

package server

import (
	"context"

	"demo3redis/internal/logic"
	"demo3redis/internal/svc"
	"demo3redis/types"
)

type Demo3Server struct {
	svcCtx *svc.ServiceContext
	types.UnimplementedDemo3Server
}

func NewDemo3Server(svcCtx *svc.ServiceContext) *Demo3Server {
	return &Demo3Server{
		svcCtx: svcCtx,
	}
}

func (s *Demo3Server) Get(ctx context.Context, in *types.GetReq) (*types.GetRsp, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *Demo3Server) Set(ctx context.Context, in *types.SetReq) (*types.SetRsp, error) {
	l := logic.NewSetLogic(ctx, s.svcCtx)
	return l.Set(in)
}
