// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc2.proto

package rpc2

import (
	"context"

	"demo2/app/rpc2/rpc2_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TestCReq = rpc2_pb.TestCReq
	TestCRsp = rpc2_pb.TestCRsp

	Rpc2 interface {
		TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error)
	}

	defaultRpc2 struct {
		cli zrpc.Client
	}
)

func NewRpc2(cli zrpc.Client) Rpc2 {
	return &defaultRpc2{
		cli: cli,
	}
}

func (m *defaultRpc2) TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error) {
	client := rpc2_pb.NewRpc2Client(m.cli.Conn())
	return client.TestC(ctx, in, opts...)
}
