// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: demo1.proto

package demo1

import (
	"context"

	"demo1/demo1_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Demo1Req = demo1_pb.Demo1Req
	Demo2Rsp = demo1_pb.Demo2Rsp

	Demo1 interface {
		Demo1Test(ctx context.Context, in *Demo1Req, opts ...grpc.CallOption) (*Demo2Rsp, error)
	}

	defaultDemo1 struct {
		cli zrpc.Client
	}
)

func NewDemo1(cli zrpc.Client) Demo1 {
	return &defaultDemo1{
		cli: cli,
	}
}

func (m *defaultDemo1) Demo1Test(ctx context.Context, in *Demo1Req, opts ...grpc.CallOption) (*Demo2Rsp, error) {
	client := demo1_pb.NewDemo1Client(m.cli.Conn())
	return client.Demo1Test(ctx, in, opts...)
}
