// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: demo1.proto

package server

import (
	"context"

	"demo1/demo1_pb"
	"demo1/internal/logic"
	"demo1/internal/svc"
)

type Demo1Server struct {
	svcCtx *svc.ServiceContext
	demo1_pb.UnimplementedDemo1Server
}

func NewDemo1Server(svcCtx *svc.ServiceContext) *Demo1Server {
	return &Demo1Server{
		svcCtx: svcCtx,
	}
}

func (s *Demo1Server) Demo1Test(ctx context.Context, in *demo1_pb.Demo1Req) (*demo1_pb.Demo2Rsp, error) {
	l := logic.NewDemo1testLogic(ctx, s.svcCtx)
	return l.Demo1Test(in)
}
