// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	demo6 "demo6/internal/handler/demo6"
	"demo6/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 测试api
				Method:  http.MethodPost,
				Path:    "/testapi",
				Handler: demo6.TestapiHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/demo6"),
	)
}
