// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: demo3.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Demo3_Get_FullMethodName = "/demo3.demo3/Get"
	Demo3_Set_FullMethodName = "/demo3.demo3/Set"
)

// Demo3Client is the client API for Demo3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Demo3Client interface {
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error)
	Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRsp, error)
}

type demo3Client struct {
	cc grpc.ClientConnInterface
}

func NewDemo3Client(cc grpc.ClientConnInterface) Demo3Client {
	return &demo3Client{cc}
}

func (c *demo3Client) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRsp)
	err := c.cc.Invoke(ctx, Demo3_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demo3Client) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRsp)
	err := c.cc.Invoke(ctx, Demo3_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Demo3Server is the server API for Demo3 service.
// All implementations must embed UnimplementedDemo3Server
// for forward compatibility.
type Demo3Server interface {
	Get(context.Context, *GetReq) (*GetRsp, error)
	Set(context.Context, *SetReq) (*SetRsp, error)
	mustEmbedUnimplementedDemo3Server()
}

// UnimplementedDemo3Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemo3Server struct{}

func (UnimplementedDemo3Server) Get(context.Context, *GetReq) (*GetRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDemo3Server) Set(context.Context, *SetReq) (*SetRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDemo3Server) mustEmbedUnimplementedDemo3Server() {}
func (UnimplementedDemo3Server) testEmbeddedByValue()               {}

// UnsafeDemo3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Demo3Server will
// result in compilation errors.
type UnsafeDemo3Server interface {
	mustEmbedUnimplementedDemo3Server()
}

func RegisterDemo3Server(s grpc.ServiceRegistrar, srv Demo3Server) {
	// If the following call panics, it indicates UnimplementedDemo3Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Demo3_ServiceDesc, srv)
}

func _Demo3_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo3Server).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demo3_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo3Server).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo3_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo3Server).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demo3_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo3Server).Set(ctx, req.(*SetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Demo3_ServiceDesc is the grpc.ServiceDesc for Demo3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demo3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo3.demo3",
	HandlerType: (*Demo3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Demo3_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Demo3_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo3.proto",
}
