// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: demo3.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_demo3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_demo3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_demo3_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRsp) Reset() {
	*x = GetRsp{}
	mi := &file_demo3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRsp) ProtoMessage() {}

func (x *GetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_demo3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRsp.ProtoReflect.Descriptor instead.
func (*GetRsp) Descriptor() ([]byte, []int) {
	return file_demo3_proto_rawDescGZIP(), []int{1}
}

func (x *GetRsp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	mi := &file_demo3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_demo3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_demo3_proto_rawDescGZIP(), []int{2}
}

func (x *SetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRsp) Reset() {
	*x = SetRsp{}
	mi := &file_demo3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRsp) ProtoMessage() {}

func (x *SetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_demo3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRsp.ProtoReflect.Descriptor instead.
func (*SetRsp) Descriptor() ([]byte, []int) {
	return file_demo3_proto_rawDescGZIP(), []int{3}
}

var File_demo3_proto protoreflect.FileDescriptor

const file_demo3_proto_rawDesc = "" +
	"\n" +
	"\vdemo3.proto\x12\x05demo3\"\x1a\n" +
	"\x06GetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1e\n" +
	"\x06GetRsp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"0\n" +
	"\x06SetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\b\n" +
	"\x06SetRsp2Q\n" +
	"\x05demo3\x12#\n" +
	"\x03Get\x12\r.demo3.GetReq\x1a\r.demo3.GetRsp\x12#\n" +
	"\x03Set\x12\r.demo3.SetReq\x1a\r.demo3.SetRspB\tZ\a./typesb\x06proto3"

var (
	file_demo3_proto_rawDescOnce sync.Once
	file_demo3_proto_rawDescData []byte
)

func file_demo3_proto_rawDescGZIP() []byte {
	file_demo3_proto_rawDescOnce.Do(func() {
		file_demo3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo3_proto_rawDesc), len(file_demo3_proto_rawDesc)))
	})
	return file_demo3_proto_rawDescData
}

var file_demo3_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_demo3_proto_goTypes = []any{
	(*GetReq)(nil), // 0: demo3.GetReq
	(*GetRsp)(nil), // 1: demo3.GetRsp
	(*SetReq)(nil), // 2: demo3.SetReq
	(*SetRsp)(nil), // 3: demo3.SetRsp
}
var file_demo3_proto_depIdxs = []int32{
	0, // 0: demo3.demo3.Get:input_type -> demo3.GetReq
	2, // 1: demo3.demo3.Set:input_type -> demo3.SetReq
	1, // 2: demo3.demo3.Get:output_type -> demo3.GetRsp
	3, // 3: demo3.demo3.Set:output_type -> demo3.SetRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo3_proto_init() }
func file_demo3_proto_init() {
	if File_demo3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo3_proto_rawDesc), len(file_demo3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo3_proto_goTypes,
		DependencyIndexes: file_demo3_proto_depIdxs,
		MessageInfos:      file_demo3_proto_msgTypes,
	}.Build()
	File_demo3_proto = out.File
	file_demo3_proto_goTypes = nil
	file_demo3_proto_depIdxs = nil
}
