// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: rpc2.proto

package rpc2_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rpc2_TestC_FullMethodName = "/rpc2.Rpc2/TestC"
)

// Rpc2Client is the client API for Rpc2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Rpc2Client interface {
	TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error)
}

type rpc2Client struct {
	cc grpc.ClientConnInterface
}

func NewRpc2Client(cc grpc.ClientConnInterface) Rpc2Client {
	return &rpc2Client{cc}
}

func (c *rpc2Client) TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestCRsp)
	err := c.cc.Invoke(ctx, Rpc2_TestC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Rpc2Server is the server API for Rpc2 service.
// All implementations must embed UnimplementedRpc2Server
// for forward compatibility.
type Rpc2Server interface {
	TestC(context.Context, *TestCReq) (*TestCRsp, error)
	mustEmbedUnimplementedRpc2Server()
}

// UnimplementedRpc2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpc2Server struct{}

func (UnimplementedRpc2Server) TestC(context.Context, *TestCReq) (*TestCRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestC not implemented")
}
func (UnimplementedRpc2Server) mustEmbedUnimplementedRpc2Server() {}
func (UnimplementedRpc2Server) testEmbeddedByValue()              {}

// UnsafeRpc2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Rpc2Server will
// result in compilation errors.
type UnsafeRpc2Server interface {
	mustEmbedUnimplementedRpc2Server()
}

func RegisterRpc2Server(s grpc.ServiceRegistrar, srv Rpc2Server) {
	// If the following call panics, it indicates UnimplementedRpc2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rpc2_ServiceDesc, srv)
}

func _Rpc2_TestC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rpc2Server).TestC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc2_TestC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rpc2Server).TestC(ctx, req.(*TestCReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpc2_ServiceDesc is the grpc.ServiceDesc for Rpc2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpc2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc2.Rpc2",
	HandlerType: (*Rpc2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestC",
			Handler:    _Rpc2_TestC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc2.proto",
}
