// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc2.proto

package server

import (
	"context"

	"demo2/app/rpc2/internal/logic"
	"demo2/app/rpc2/internal/svc"
	"demo2/app/rpc2/rpc2_pb"
)

type Rpc2Server struct {
	svcCtx *svc.ServiceContext
	rpc2_pb.UnimplementedRpc2Server
}

func NewRpc2Server(svcCtx *svc.ServiceContext) *Rpc2Server {
	return &Rpc2Server{
		svcCtx: svcCtx,
	}
}

func (s *Rpc2Server) TestC(ctx context.Context, in *rpc2_pb.TestCReq) (*rpc2_pb.TestCRsp, error) {
	l := logic.NewTestCLogic(ctx, s.svcCtx)
	return l.TestC(in)
}
