// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: rpc1.proto

package rpc1_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputParams   string                 `protobuf:"bytes,1,opt,name=input_params,json=inputParams,proto3" json:"input_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCReq) Reset() {
	*x = TestCReq{}
	mi := &file_rpc1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCReq) ProtoMessage() {}

func (x *TestCReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCReq.ProtoReflect.Descriptor instead.
func (*TestCReq) Descriptor() ([]byte, []int) {
	return file_rpc1_proto_rawDescGZIP(), []int{0}
}

func (x *TestCReq) GetInputParams() string {
	if x != nil {
		return x.InputParams
	}
	return ""
}

type TestCRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputParams  string                 `protobuf:"bytes,2,opt,name=output_params,json=outputParams,proto3" json:"output_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCRsp) Reset() {
	*x = TestCRsp{}
	mi := &file_rpc1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCRsp) ProtoMessage() {}

func (x *TestCRsp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCRsp.ProtoReflect.Descriptor instead.
func (*TestCRsp) Descriptor() ([]byte, []int) {
	return file_rpc1_proto_rawDescGZIP(), []int{1}
}

func (x *TestCRsp) GetOutputParams() string {
	if x != nil {
		return x.OutputParams
	}
	return ""
}

var File_rpc1_proto protoreflect.FileDescriptor

const file_rpc1_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rpc1.proto\x12\x04rpc1\"-\n" +
	"\bTestCReq\x12!\n" +
	"\finput_params\x18\x01 \x01(\tR\vinputParams\"/\n" +
	"\bTestCRsp\x12#\n" +
	"\routput_params\x18\x02 \x01(\tR\foutputParams2/\n" +
	"\x04Rpc1\x12'\n" +
	"\x05TestC\x12\x0e.rpc1.TestCReq\x1a\x0e.rpc1.TestCRspB\vZ\t./rpc1_pbb\x06proto3"

var (
	file_rpc1_proto_rawDescOnce sync.Once
	file_rpc1_proto_rawDescData []byte
)

func file_rpc1_proto_rawDescGZIP() []byte {
	file_rpc1_proto_rawDescOnce.Do(func() {
		file_rpc1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc1_proto_rawDesc), len(file_rpc1_proto_rawDesc)))
	})
	return file_rpc1_proto_rawDescData
}

var file_rpc1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc1_proto_goTypes = []any{
	(*TestCReq)(nil), // 0: rpc1.TestCReq
	(*TestCRsp)(nil), // 1: rpc1.TestCRsp
}
var file_rpc1_proto_depIdxs = []int32{
	0, // 0: rpc1.Rpc1.TestC:input_type -> rpc1.TestCReq
	1, // 1: rpc1.Rpc1.TestC:output_type -> rpc1.TestCRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc1_proto_init() }
func file_rpc1_proto_init() {
	if File_rpc1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc1_proto_rawDesc), len(file_rpc1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc1_proto_goTypes,
		DependencyIndexes: file_rpc1_proto_depIdxs,
		MessageInfos:      file_rpc1_proto_msgTypes,
	}.Build()
	File_rpc1_proto = out.File
	file_rpc1_proto_goTypes = nil
	file_rpc1_proto_depIdxs = nil
}
