// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: rpc1.proto

package rpc1_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rpc1_TestC_FullMethodName = "/rpc1.Rpc1/TestC"
)

// Rpc1Client is the client API for Rpc1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Rpc1Client interface {
	TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error)
}

type rpc1Client struct {
	cc grpc.ClientConnInterface
}

func NewRpc1Client(cc grpc.ClientConnInterface) Rpc1Client {
	return &rpc1Client{cc}
}

func (c *rpc1Client) TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestCRsp)
	err := c.cc.Invoke(ctx, Rpc1_TestC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Rpc1Server is the server API for Rpc1 service.
// All implementations must embed UnimplementedRpc1Server
// for forward compatibility.
type Rpc1Server interface {
	TestC(context.Context, *TestCReq) (*TestCRsp, error)
	mustEmbedUnimplementedRpc1Server()
}

// UnimplementedRpc1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpc1Server struct{}

func (UnimplementedRpc1Server) TestC(context.Context, *TestCReq) (*TestCRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestC not implemented")
}
func (UnimplementedRpc1Server) mustEmbedUnimplementedRpc1Server() {}
func (UnimplementedRpc1Server) testEmbeddedByValue()              {}

// UnsafeRpc1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Rpc1Server will
// result in compilation errors.
type UnsafeRpc1Server interface {
	mustEmbedUnimplementedRpc1Server()
}

func RegisterRpc1Server(s grpc.ServiceRegistrar, srv Rpc1Server) {
	// If the following call panics, it indicates UnimplementedRpc1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rpc1_ServiceDesc, srv)
}

func _Rpc1_TestC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Rpc1Server).TestC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc1_TestC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Rpc1Server).TestC(ctx, req.(*TestCReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpc1_ServiceDesc is the grpc.ServiceDesc for Rpc1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpc1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc1.Rpc1",
	HandlerType: (*Rpc1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestC",
			Handler:    _Rpc1_TestC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc1.proto",
}
