// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: demo1.proto

package demo1_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Demo1Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputParams   string                 `protobuf:"bytes,1,opt,name=input_params,json=inputParams,proto3" json:"input_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo1Req) Reset() {
	*x = Demo1Req{}
	mi := &file_demo1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo1Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo1Req) ProtoMessage() {}

func (x *Demo1Req) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo1Req.ProtoReflect.Descriptor instead.
func (*Demo1Req) Descriptor() ([]byte, []int) {
	return file_demo1_proto_rawDescGZIP(), []int{0}
}

func (x *Demo1Req) GetInputParams() string {
	if x != nil {
		return x.InputParams
	}
	return ""
}

type Demo2Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputParams  string                 `protobuf:"bytes,2,opt,name=output_params,json=outputParams,proto3" json:"output_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo2Rsp) Reset() {
	*x = Demo2Rsp{}
	mi := &file_demo1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo2Rsp) ProtoMessage() {}

func (x *Demo2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo2Rsp.ProtoReflect.Descriptor instead.
func (*Demo2Rsp) Descriptor() ([]byte, []int) {
	return file_demo1_proto_rawDescGZIP(), []int{1}
}

func (x *Demo2Rsp) GetOutputParams() string {
	if x != nil {
		return x.OutputParams
	}
	return ""
}

var File_demo1_proto protoreflect.FileDescriptor

const file_demo1_proto_rawDesc = "" +
	"\n" +
	"\vdemo1.proto\x12\x05demo1\"-\n" +
	"\bDemo1Req\x12!\n" +
	"\finput_params\x18\x01 \x01(\tR\vinputParams\"/\n" +
	"\bDemo2Rsp\x12#\n" +
	"\routput_params\x18\x02 \x01(\tR\foutputParams26\n" +
	"\x05demo1\x12-\n" +
	"\tdemo1test\x12\x0f.demo1.Demo1Req\x1a\x0f.demo1.Demo2RspB\fZ\n" +
	"./demo1_pbb\x06proto3"

var (
	file_demo1_proto_rawDescOnce sync.Once
	file_demo1_proto_rawDescData []byte
)

func file_demo1_proto_rawDescGZIP() []byte {
	file_demo1_proto_rawDescOnce.Do(func() {
		file_demo1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo1_proto_rawDesc), len(file_demo1_proto_rawDesc)))
	})
	return file_demo1_proto_rawDescData
}

var file_demo1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demo1_proto_goTypes = []any{
	(*Demo1Req)(nil), // 0: demo1.Demo1Req
	(*Demo2Rsp)(nil), // 1: demo1.Demo2Rsp
}
var file_demo1_proto_depIdxs = []int32{
	0, // 0: demo1.demo1.demo1test:input_type -> demo1.Demo1Req
	1, // 1: demo1.demo1.demo1test:output_type -> demo1.Demo2Rsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo1_proto_init() }
func file_demo1_proto_init() {
	if File_demo1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo1_proto_rawDesc), len(file_demo1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo1_proto_goTypes,
		DependencyIndexes: file_demo1_proto_depIdxs,
		MessageInfos:      file_demo1_proto_msgTypes,
	}.Build()
	File_demo1_proto = out.File
	file_demo1_proto_goTypes = nil
	file_demo1_proto_depIdxs = nil
}
