// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: demo1.proto

package demo1_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Demo1_Demo1Test_FullMethodName = "/demo1.demo1/demo1test"
)

// Demo1Client is the client API for Demo1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Demo1Client interface {
	Demo1Test(ctx context.Context, in *Demo1Req, opts ...grpc.CallOption) (*Demo2Rsp, error)
}

type demo1Client struct {
	cc grpc.ClientConnInterface
}

func NewDemo1Client(cc grpc.ClientConnInterface) Demo1Client {
	return &demo1Client{cc}
}

func (c *demo1Client) Demo1Test(ctx context.Context, in *Demo1Req, opts ...grpc.CallOption) (*Demo2Rsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Demo2Rsp)
	err := c.cc.Invoke(ctx, Demo1_Demo1Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Demo1Server is the server API for Demo1 service.
// All implementations must embed UnimplementedDemo1Server
// for forward compatibility.
type Demo1Server interface {
	Demo1Test(context.Context, *Demo1Req) (*Demo2Rsp, error)
	mustEmbedUnimplementedDemo1Server()
}

// UnimplementedDemo1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemo1Server struct{}

func (UnimplementedDemo1Server) Demo1Test(context.Context, *Demo1Req) (*Demo2Rsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Demo1Test not implemented")
}
func (UnimplementedDemo1Server) mustEmbedUnimplementedDemo1Server() {}
func (UnimplementedDemo1Server) testEmbeddedByValue()               {}

// UnsafeDemo1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Demo1Server will
// result in compilation errors.
type UnsafeDemo1Server interface {
	mustEmbedUnimplementedDemo1Server()
}

func RegisterDemo1Server(s grpc.ServiceRegistrar, srv Demo1Server) {
	// If the following call panics, it indicates UnimplementedDemo1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Demo1_ServiceDesc, srv)
}

func _Demo1_Demo1Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Demo1Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo1Server).Demo1Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demo1_Demo1Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo1Server).Demo1Test(ctx, req.(*Demo1Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Demo1_ServiceDesc is the grpc.ServiceDesc for Demo1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demo1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo1.demo1",
	HandlerType: (*Demo1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "demo1test",
			Handler:    _Demo1_Demo1Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo1.proto",
}
