// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc1.proto

package rpc1

import (
	"context"

	"demo2/app/rpc1/rpc1_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TestCReq = rpc1_pb.TestCReq
	TestCRsp = rpc1_pb.TestCRsp

	Rpc1 interface {
		TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error)
	}

	defaultRpc1 struct {
		cli zrpc.Client
	}
)

func NewRpc1(cli zrpc.Client) Rpc1 {
	return &defaultRpc1{
		cli: cli,
	}
}

func (m *defaultRpc1) TestC(ctx context.Context, in *TestCReq, opts ...grpc.CallOption) (*TestCRsp, error) {
	client := rpc1_pb.NewRpc1Client(m.cli.Conn())
	return client.TestC(ctx, in, opts...)
}
