// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_mgr.proto

package server

import (
	"context"

	"demo4mysql/internal/logic"
	"demo4mysql/internal/svc"
	"demo4mysql/user_mgr_pb"
)

type UserMgrServer struct {
	svcCtx *svc.ServiceContext
	user_mgr_pb.UnimplementedUserMgrServer
}

func NewUserMgrServer(svcCtx *svc.ServiceContext) *UserMgrServer {
	return &UserMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *UserMgrServer) CreateUser(ctx context.Context, in *user_mgr_pb.CreateUserReq) (*user_mgr_pb.CreateUserRsp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserMgrServer) GetUser(ctx context.Context, in *user_mgr_pb.GetUserReq) (*user_mgr_pb.GetUserRsp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserMgrServer) UpdateUser(ctx context.Context, in *user_mgr_pb.UpdateUserReq) (*user_mgr_pb.UpdateUserRsp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserMgrServer) DeleteUser(ctx context.Context, in *user_mgr_pb.DeleteUserReq) (*user_mgr_pb.DeleteUserRsp, error) {
	l := logic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *UserMgrServer) GetAllUsers(ctx context.Context, in *user_mgr_pb.GetAllUsersReq) (*user_mgr_pb.GetAllUsersRsp, error) {
	l := logic.NewGetAllUsersLogic(ctx, s.svcCtx)
	return l.GetAllUsers(in)
}
