// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: user_mgr.proto

package user_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建用户Req
type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_user_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// 创建用户Req
type CreateUserRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,2,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRsp) Reset() {
	*x = CreateUserRsp{}
	mi := &file_user_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRsp) ProtoMessage() {}

func (x *CreateUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRsp.ProtoReflect.Descriptor instead.
func (*CreateUserRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_user_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRsp) Reset() {
	*x = GetUserInfoRsp{}
	mi := &file_user_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRsp) ProtoMessage() {}

func (x *GetUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoRsp) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type GetUserBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReq) Reset() {
	*x = GetUserBalanceReq{}
	mi := &file_user_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReq) ProtoMessage() {}

func (x *GetUserBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBalanceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserBalanceRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRsp) Reset() {
	*x = GetUserBalanceRsp{}
	mi := &file_user_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRsp) ProtoMessage() {}

func (x *GetUserBalanceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRsp.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBalanceRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBalanceRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 充值
type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_user_mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{6}
}

func (x *DepositReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DepositRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRsp) Reset() {
	*x = DepositRsp{}
	mi := &file_user_mgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRsp) ProtoMessage() {}

func (x *DepositRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRsp.ProtoReflect.Descriptor instead.
func (*DepositRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{7}
}

func (x *DepositRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 提现
type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_user_mgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WithdrawReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRsp) Reset() {
	*x = WithdrawRsp{}
	mi := &file_user_mgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRsp) ProtoMessage() {}

func (x *WithdrawRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRsp.ProtoReflect.Descriptor instead.
func (*WithdrawRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WithdrawRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_user_mgr_proto protoreflect.FileDescriptor

const file_user_mgr_proto_rawDesc = "" +
	"\n" +
	"\x0euser_mgr.proto\x12\buser_mgr\"N\n" +
	"\rCreateUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"E\n" +
	"\rCreateUserRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_repeat\x18\x02 \x01(\x05R\bisRepeat\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x0eGetUserInfoRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\",\n" +
	"\x11GetUserBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x11GetUserBalanceRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"=\n" +
	"\n" +
	"DepositReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"?\n" +
	"\n" +
	"DepositRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\">\n" +
	"\vWithdrawReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"@\n" +
	"\vWithdrawRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance2\xc9\x02\n" +
	"\aUserMgr\x12>\n" +
	"\n" +
	"CreateUser\x12\x17.user_mgr.CreateUserReq\x1a\x17.user_mgr.CreateUserRsp\x12A\n" +
	"\vGetUserInfo\x12\x18.user_mgr.GetUserInfoReq\x1a\x18.user_mgr.GetUserInfoRsp\x12J\n" +
	"\x0eGetUserBalance\x12\x1b.user_mgr.GetUserBalanceReq\x1a\x1b.user_mgr.GetUserBalanceRsp\x125\n" +
	"\aDeposit\x12\x14.user_mgr.DepositReq\x1a\x14.user_mgr.DepositRsp\x128\n" +
	"\bWithdraw\x12\x15.user_mgr.WithdrawReq\x1a\x15.user_mgr.WithdrawRspB\x0fZ\r./user_mgr_pbb\x06proto3"

var (
	file_user_mgr_proto_rawDescOnce sync.Once
	file_user_mgr_proto_rawDescData []byte
)

func file_user_mgr_proto_rawDescGZIP() []byte {
	file_user_mgr_proto_rawDescOnce.Do(func() {
		file_user_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_mgr_proto_rawDesc), len(file_user_mgr_proto_rawDesc)))
	})
	return file_user_mgr_proto_rawDescData
}

var file_user_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_mgr_proto_goTypes = []any{
	(*CreateUserReq)(nil),     // 0: user_mgr.CreateUserReq
	(*CreateUserRsp)(nil),     // 1: user_mgr.CreateUserRsp
	(*GetUserInfoReq)(nil),    // 2: user_mgr.GetUserInfoReq
	(*GetUserInfoRsp)(nil),    // 3: user_mgr.GetUserInfoRsp
	(*GetUserBalanceReq)(nil), // 4: user_mgr.GetUserBalanceReq
	(*GetUserBalanceRsp)(nil), // 5: user_mgr.GetUserBalanceRsp
	(*DepositReq)(nil),        // 6: user_mgr.DepositReq
	(*DepositRsp)(nil),        // 7: user_mgr.DepositRsp
	(*WithdrawReq)(nil),       // 8: user_mgr.WithdrawReq
	(*WithdrawRsp)(nil),       // 9: user_mgr.WithdrawRsp
}
var file_user_mgr_proto_depIdxs = []int32{
	0, // 0: user_mgr.UserMgr.CreateUser:input_type -> user_mgr.CreateUserReq
	2, // 1: user_mgr.UserMgr.GetUserInfo:input_type -> user_mgr.GetUserInfoReq
	4, // 2: user_mgr.UserMgr.GetUserBalance:input_type -> user_mgr.GetUserBalanceReq
	6, // 3: user_mgr.UserMgr.Deposit:input_type -> user_mgr.DepositReq
	8, // 4: user_mgr.UserMgr.Withdraw:input_type -> user_mgr.WithdrawReq
	1, // 5: user_mgr.UserMgr.CreateUser:output_type -> user_mgr.CreateUserRsp
	3, // 6: user_mgr.UserMgr.GetUserInfo:output_type -> user_mgr.GetUserInfoRsp
	5, // 7: user_mgr.UserMgr.GetUserBalance:output_type -> user_mgr.GetUserBalanceRsp
	7, // 8: user_mgr.UserMgr.Deposit:output_type -> user_mgr.DepositRsp
	9, // 9: user_mgr.UserMgr.Withdraw:output_type -> user_mgr.WithdrawRsp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_mgr_proto_init() }
func file_user_mgr_proto_init() {
	if File_user_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_mgr_proto_rawDesc), len(file_user_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_mgr_proto_goTypes,
		DependencyIndexes: file_user_mgr_proto_depIdxs,
		MessageInfos:      file_user_mgr_proto_msgTypes,
	}.Build()
	File_user_mgr_proto = out.File
	file_user_mgr_proto_goTypes = nil
	file_user_mgr_proto_depIdxs = nil
}
